### ISSUE TITLE
Could not find ground truth data（pbmc.g949_c10k.msk90.hd5）

### ISSUE THREAD

**Issue by lovivi** [audreyqyfu/LATE#3]
` File ../data/pbmc.g949_c10k.msk90.hd5 does not exist`
In the article, the actual value of the group is sampled, and I can't get the corresponding real data, which is difficult to compare. 

> We focused on the same 949 genes as in the PBMC_G949 data set, subsampled 10K cells while retaining the relative frequencies of the ten cell types

**Comment by audreyqyfu** [comment]
The subsampled 10K cells are in example.hd5, and the input generated from this ground truth is example.msk90.hd5.  I updated README to reflect this info.
