### ISSUE TITLE
error in "> DATA TRANSFORMATION.."

### ISSUE THREAD

**Issue by eijynagai** [audreyqyfu/LATE#4]
Hi,

I'm running LATE in scRNA-seq published data (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126954). I've tested the sample data and worked fine with LATE. Then I also tested successfully a SAVERX sample test. However, when I tried to run on my data I got the following error:

> DATA TRANSFORMATION..
Traceback (most recent call last):
  File "example_late.py", line 36, in <module>
    late.late_main(p, log_dir, rand_state = 3)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/late.py", line 216, in late_main
    input_matrix, gene_ids, cell_ids = read_data(p)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/late.py", line 709, in read_data
    transformation=p.transformation_input
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/scimpute.py", line 291, in df_transformation
    df = df_log10_transformation(df)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/scimpute.py", line 232, in df_log10_transformation
    df_log10 = np.log10(np.add(df, pseudocount))
TypeError: must be str, not int

I'm using the csv input generated by a script from cellranger to convert MEX type to csv.

I would appreciate if you could help me.

Thank you.

Eijy

**Comment by audreyqyfu** [comment]
Hi Eijy,

Thanks for trying our software.  I will look into it.

Best,
Audrey

**Comment by audreyqyfu** [comment]
Hi Eijy,

I wonder whether the csv converted from MEX has a different format than the format we use for LATE.  I have added a small csv data file under the data/ folder.  Regardless of the file format, the input is a cell-by-gene matrix.  

I did a quick search of MEX conversion and saw this page: https://kb.10xgenomics.com/hc/en-us/articles/360023793031-How-can-I-convert-the-feature-barcode-matrix-from-Cell-Ranger-3-x-to-a-CSV-file-  

The final csv file on this webpage looks like this:
AAACCTGCACATTAGC-1,ENSG00000005075,POLR2J,Gene Expression,1
AAACCTGCACATTAGC-1,ENSG00000006015,C19orf60,Gene Expression,1
AAACCTGCACATTAGC-1,ENSG00000007944,MYLIP,Gene Expression,2

This is not the format LATE can work with.  You may need to convert this csv file again to generate a csv file like this:
gene1,gene2,gene3
cell1,0,0,1
cell2,0,1,0

Hope this helps.

Audrey

**Comment by eijynagai** [comment]
Hi,

That's probably the case! Sorry, I didn't realize that.
I will create modify the script and test. I let you know if it works.

Thank you very much!

Eijy

**Comment by eijynagai** [comment]
Sorry for the late reply. You're right, the input file was wrong. I used a R package 'DropletUtils', with the function 'write10xCounts' to convert to hdf5 format. Thank you for your suggestion!
