### ISSUE TITLE
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/WBcel235``

### ISSUE THREAD

**Issue by eijynagai** [audreyqyfu/LATE#5]
Hi,

I'm trying to run late as following, but end up getting this error. I wonder if late can work if other kinds of organisms than mouse and human data. I tried to adjust the global_params.py file for C. elegans genome but it didn't work.

I would appreciate your help.

Eijy 

$ python example_late.py -mode='late' -infile='../../DATA/LATE_matrix.h5'
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

mode: late

Data:
fname_input: ../../DATA/LATE_matrix.h5
name_input: example
ori_input: cell_row
transformation_input: log10
data split: [0.7/0.15/0.15]

Parameters:
mse_mode: mse_nz
stage: step2
init: rand_init
test_mode: False
total number of layers: 5
n_hidden1: 800
n_hidden2: 400
learning_rate: 0.0003
reg_coef: 0.0
batch_size: 256
sample_zie:  1000
pIn: 0.8
pHidden: 0.5
max_training_epochs: 20
display_step 10
snapshot_step 10

./step2 deleted
./step2 created

>READING DATA..
RAM usage before reading data: 157.2 M
reading ../../DATA/LATE_matrix.h5 WBcel235
Traceback (most recent call last):
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/scimpute.py", line 108, in read_sparse_matrix_from_h5
    for node in f.walk_nodes('/' + genome, 'Array'):
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/file.py", line 2119, in walk_nodes
    for group in self.walk_groups(where):
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/file.py", line 2137, in walk_groups
    group = self.get_node(where)  # Does the parent exist?
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/home/nagailae/local/share/bcbio/anaconda/envs/py36/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/WBcel235``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_late.py", line 36, in <module>
    late.late_main(p, log_dir, rand_state = 3)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/late.py", line 216, in late_main
    input_matrix, gene_ids, cell_ids = read_data(p)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/late.py", line 675, in read_data
    p.ori_input)
  File "/yshare3/home/nagailae/projects/sc_celegans/translate/LATE/scripts/scimpute.py", line 132, in read_sparse_matrix_from_h5
    raise Exception("Genome %s does not exist in this file." % genome)
Exception: Genome WBcel235 does not exist in this file.

**Comment by audreyqyfu** [comment]
That's a good question.  I'll look into this tomorrow.

**Comment by audreyqyfu** [comment]
I saw in your comment to the earlier thread that you had converted the input into hdf5.  If so, you do not need to modify the global parameters and can use example_late.py, and run LATE on this file directly.  hdf5 is the same as the hd5 format of most of the sample data under data/ (except for example_mouse_brain_10x.h5).  They are different from h5, which is specific to data directly provided by 10x.

Hope this helps.

Best,
Audrey

**Comment by eijynagai** [comment]
Hi Audrey,

Thank you so much! Yes, you're right. the function write10xCounts can write count data in the hdf5 and h5. To export in hdf5 one should use the parameter "version = 3", I mistakenly saved as .hd5 using "version = 2" (which is h5 format). 

So, after adapting to 10x h5 format, I ran the command "python example_late_10x.py -mode='late' -infile='../../../seurat3/LATE_matrix.h5'" and it now worked.

Thank you so much!

Eijy

**Comment by audreyqyfu** [comment]
Hi Eijy,

That's interesting.  Thanks for letting me know.  

Our algorithm doesn't depend on the genome.  I think that the genome_input parameter in global_params.py is more about parsing the h5 format.  

In any case, thanks again for your interest in our software and your feedback!

Best,
Audrey
