### ISSUE TITLE
How to generate ground truth data?

### ISSUE THREAD

**Issue by AnwarKhan345** [audreyqyfu/LATE#6]
With profound reverence, I couldn't understand how to generate ground truth data via masking?

**Comment by audreyqyfu** [comment]
Thanks for your interest.  We apply masking to the ground truth to generate input data that are similar to real single-cell data.  Ground truth usually does not have zeros, or not too many zeros.  

Take the following five data points for example: 0.5, 1.2, 0.7, 0.3, 2.4.  These data points are the ground truth.  By masking, it means that we want to convert say, three data points to zero.  We do this by randomly picking three data points.  If data points #1, #4 and #5 are chosen, then we have 0, 1.2, 0.7, 0, 0 as the masked data.  Then we can use the masked data as the input, while we know the real values behind those three 0s.  

Hope this helps.

Audrey

**Comment by AnwarKhan345** [comment]
Thank you so much for your time and consideration. 
I fully understand your point. One thing which is causing the problem is the scImpute, R package. 
Whenever I call 
nz_rate = scimpute.nnzero_rate_df(df)
it shows a name error called: name 'scimpute' is not defined.

Though, I successfully installed the R package via rpy2 command.

**Comment by audreyqyfu** [comment]
scimpute here refers to our own library scimpute.py under scripts/, not the R package.  Did you import our library in Python using 'import scimpute'?
